
service: image-handler

frameworkVersion: '3'

provider:
  name: aws
  runtime: java17
  stage: ${opt:stage, 'dev'}
  environment:
    bucketName: ${self:custom.bucketName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: '*'

package:
  artifact: target/scala-2.13/image-handler.jar

custom:
  bucketName: cats-gallery

functions:
  hello:
    handler: hello.ApiGatewayHandler
    events:
      - http:
          path: hello
          method: get
  getDailyImage:
    handler: lambdas.endpoints.GetDailyImageHandler
    timeout: 30
    events:
      - http:
          path: cats/daily
          method: get
  getRandomImage:
    handler: lambdas.endpoints.GetRandomImageHandler
    timeout: 30
    events:
      - http:
          path: cats/random
          method: get