name: Reusable workflow

on:
  workflow_call:
    inputs:
      stage:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      OPENAI_API_KEY:
        required: true

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Append to file
        uses: DamianReeves/write-file-action@master
        with:
          path: ./src/main/resources/application.conf
          contents: |
            \n openAiApiKey = ${{ secrets.OPENAI_API_KEY }}
          write-mode: append

      - name: Setup Scala
        uses: olafurpg/setup-scala@v12
        with:
          java-version: adopt@1.14

      - name: Build project
        run: sbt assembly

      - name: serverless deploy
        uses: serverless/github-action@v3.2
        with:
          args: deploy --stage ${{ inputs.stage }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}